# Generated by Django 2.2.6 on 2019-10-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('blog', '0004_remove_post_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
