# Generated by Django 2.2.6 on 2019-10-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191023_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(default='img/noite2.jpeg', upload_to='imagens_publicacao'),
            preserve_default=False,
        ),
    ]
