# Generated by Django 2.2.6 on 2019-10-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_publicacao_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
