# Generated by Django 2.2.6 on 2019-11-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
