# Generated by Django 2.2.6 on 2019-11-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Categoria'),
            preserve_default=False,
        ),
    ]
