# Generated by Django 2.2.6 on 2019-11-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_publicacao_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='condicao',
            field=models.IntegerField(choices=[(0, 'Rascunho'), (1, 'Publicar')], default=0, verbose_name='Condição'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima alteração'),
        ),
    ]
