# Generated by Django 2.2.6 on 2019-11-02 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20191102_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Tag'),
            preserve_default=False,
        ),
    ]
