# Generated by Django 2.2.6 on 2019-11-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_publicacao_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='Publicacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Publicacao'),
            preserve_default=False,
        ),
    ]
