# Generated by Django 2.2.6 on 2019-11-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20191102_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='publicacoes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='blog.Publicacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='Publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.Publicacao'),
        ),
    ]
