# Generated by Django 2.2.6 on 2019-11-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20191105_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='blog.Tag'),
        ),
    ]
