# Generated by Django 2.2.6 on 2019-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_publicacao_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='tag',
            field=models.ManyToManyField(related_name='publicacoes', to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Publicacao',
            field=models.ManyToManyField(related_name='publicacao', to='blog.Publicacao'),
        ),
    ]
