# Generated by Django 2.2.6 on 2019-11-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20191106_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Publicacao',
        ),
    ]
