# Generated by Django 2.2.6 on 2019-11-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_tag_publicacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViwerEmail',
        ),
    ]
