# Generated by Django 2.2.6 on 2019-11-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_delete_viweremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViwerEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('notificado', models.BooleanField(default=False)),
            ],
        ),
    ]
